### ISSUE TITLE
Issues with the site and script

### ISSUE THREAD

**Issue by EmidioStani** [sparna-git/xls2rdf#37]
Hello @tfrancart ,

I tried to use contact form on the sparna site but I keep getting the error :
Erreur lors de l'envoi du message. Veuillez réessayer plus tard ou contacter l'administrateur d'une autre manière.

A small thing: the button "Essayer" in the page http://labs.sparna.fr/ for SHACL Play! brings to Sparnatural Demo

Last, I created a script prototype that starts from SHACL shapes and generates an excel in the format used by xls2rdf:
https://github.com/EmidioStani/shacl2spreadsheet

so when the model changes the spreadsheet is updated

**Comment by tfrancart** [comment]
> I tried to use contact form on the sparna site but I keep getting the error :
< Erreur lors de l'envoi du message. Veuillez réessayer plus tard ou contacter l'administrateur d'une autre manière.

Are we talking about http://www.sparna.fr/contact/ ? I just tested it and it works for me.
Anyway, you have reached me :-) Github issues are fine.

> A small thing: the button "Essayer" in the page http://labs.sparna.fr/ for SHACL Play! brings to Sparnatural Demo

Fixed, thanks

> Last, I created a script prototype that starts from SHACL shapes and generates an excel in the format used by xls2rdf:
https://github.com/EmidioStani/shacl2spreadsheet

This is great ! the next step would be to actually *populate* the Excel file with actual instances, so that we could do a roundtrip : RDF data --> Excel file --> Modify the Excel file --> Regenerate the RDF data.

I will add a pointer to your project in the README here.

You might be interested in the xls2rdf API also : http://xls2rdf.sparna.fr/rest/convert

**Comment by EmidioStani** [comment]
Thanks, 

indeed the intention of the script is to create a semi-automatic approach, so that the structure of spreadsheet is filled automatic with the RDF (SHACL) and manually by person to insert instances and then to use the API to generate final RDF.

Best,

Emidio
