### ISSUE TITLE
Avoiding duplicating column

### ISSUE THREAD

**Issue by EmidioStani** [sparna-git/xls2rdf#50]
Hello @tfrancart ,

imagine in the spreadsheet I have a column "rdf:type" to describe instances of certain classes. Now in wikidata there is <http://www.wikidata.org/entity/P31> to indicate the "instance of" relation.

So if I want to use both, I could duplicate the column of rdf:type and reusing the wikidata URI; this could be applied to any properties (e.g skos:prefLabel and rdfs:label, etc.) 

Is there a way to put both URI in the same column for example "rdf:type||wde:P31"

Thanks,

**Comment by tfrancart** [comment]
Thanks, I am transferring this issue to the xls2rdf repository.

No, it is not possible to put more than one predicate in a column. One column is mapped to one and only one predicate.

Right now, when this situation arises, don't hesitate to create another column with a formula to copy the content of the first column.
I also sometimes distinguish between a first sheet with the input data, with a simple structure, and that is not converted, and a second sheet that is formatted to be converted, and that copies the content of the first sheet in proper columns.

In order to implement this maybe in the future, I would probably use a "parameter", e.g. "copyTo", such as `rdf:type(separator="," copyTo="wd:P31")`.

**Comment by EmidioStani** [comment]
Thanks ! I will copy the columns for now
